### ISSUE TITLE
Failed to get crumb to get Crumb

### ISSUE THREAD

**Issue by born2net** [pilwon/node-yahoo-finance#65]
I am running node v6 and using the example provided and getting the following error.

any ideas?

```
Unhandled rejection Error: Failed to get crumb (cookiejar.setCookie is not a function)
    at /var/www/sites/dynasite/htdocs/_msportal/_js/_node/node_modules/yahoo-finance/lib/yahooCrumb.js:72:13
    at tryCatcher (/var/www/sites/dynasite/htdocs/_msportal/_js/_node/node_modules/request-promise/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/www/sites/dynasite/htdocs/_msportal/_js/_node/node_modules/request-promise/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/var/www/sites/dynasite/htdocs/_msportal/_js/_node/node_modules/request-promise/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/var/www/sites/dynasite/htdocs/_msportal/_js/_node/node_modules/request-promise/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/var/www/sites/dynasite/htdocs/_msportal/_js/_node/node_modules/request-promise/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/var/www/sites/dynasite/htdocs/_msportal/_js/_node/node_modules/request-promise/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/var/www/sites/dynasite/htdocs/_msportal/_js/_node/node_modules/request-promise/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/var/www/sites/dynasite/htdocs/_msportal/_js/_node/node_modules/request-promise/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues (/var/www/sites/dynasite/htdocs/_msportal/_js/_node/node_modules/request-promise/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by gadicc** [comment]
Hey @born2net, this actually sounds familiar, as I recall it had to do with `request` having only partial cookie support or with a problem with the `tough-cookie` installation.

Can you try removing `tough-cookie`, deleting `node_modules/tough-cookie`, and re-adding it back in?

I see also that tough-cookie is now at v3 whereas we built with v2, but it looks like the parts of the API we use are still the same.  Still, in case the above doesn't work, you could also try installing the latest v2 instead.  But I think the above will work, let us know.

**Comment by born2net** [comment]
that fixed it TX!

**Comment by gadicc** [comment]
Yay awesome!  Thanks for reporting back :D

**Comment by codeofsumit** [comment]
Had the same issue and this fixed it for me too 👍
