### ISSUE TITLE
(Error: Failed to download data) after trying to run this program in a loop

### ISSUE THREAD

**Issue by destroyer22719** [pilwon/node-yahoo-finance#84]
```
Error: Failed to download data (404 - {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"No fundamentals data found for any of the summaryTypes=summaryDetail,financialData,defaultKeyStatistics,summaryProfile"}}})
    at /home/nathan/Downloads/Code_Projects/investing/node_modules/yahoo-finance/lib/quote.js:146:15
    at tryCatcher (/home/nathan/Downloads/Code_Projects/investing/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/nathan/Downloads/Code_Projects/investing/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/nathan/Downloads/Code_Projects/investing/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/nathan/Downloads/Code_Projects/investing/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/nathan/Downloads/Code_Projects/investing/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/home/nathan/Downloads/Code_Projects/investing/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/nathan/Downloads/Code_Projects/investing/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/nathan/Downloads/Code_Projects/investing/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/nathan/Downloads/Code_Projects/investing/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
    ```

My code:
```js
const getData = async (name, symbol, loc) => {
    try {
        const data = await yahooFinance.quote({
            symbol,
            modules: [
                "summaryDetail",
                "defaultKeyStatistics",
                "financialData",
                "summaryProfile",
            ],
        });

       return data

     } catch (err) {
        console.log(err)
    }
};

...

for (const stock of rows) {
   const data = await getData(stock.symbol)
  console.log(data)
}
```
That above isn't exactly my code but more or less what it is.

**Comment by gadicc** [comment]
Hey @destroyer22719.  This error is because you're asking for data that doesn't exist for one of the symbols you're fetching in your loop.  You should wrap the call in a `try...catch` and then I guess then try loop over each individual module type (also in a `try...catch`) if you want to get the max amount of information possible).

I have a feeling in v2 (see the README) the errors are more descriptive and it will be easier to tell which symbols are generating these errors.

**Comment by kuworking** [comment]
This is I guess a yahoo protection(?), when I load it from the browser, for half a second I see this

![image](https://user-images.githubusercontent.com/4474004/151653158-b662186e-fcc3-407e-aa2d-b67e10ea824a.png)

And then it reloads automatically (not the entire page) and works. I think this is what makes it fail if you access through nodejs.
