### ISSUE TITLE
Unhandled rejection Error: Failed to get crumb

### ISSUE THREAD

**Issue by leebailey88** [pilwon/node-yahoo-finance#93]
This started happening on every request since a few hours ago today. Any ideas?

```
Unhandled rejection Error: Failed to get crumb (404 - "<html><meta charset='utf-8'><script>if(window!=window.top){document.write('<p>Content is currently unavailable.</p><img src=\"//geo.yahoo.com/p?s=1197757039&t='+new Date().getTime()+'&_R='+encodeURIComponent(document.referrer)+'&err=404&err_url='+'https%3A%2F%2Ffinance.yahoo.com%2Fquote%2F%255EGSPC%2Fhistory'+'\" width=\"0px\" height=\"0px\"/>');}else{window.location.replace('https://www.yahoo.com/?err=404&err_url=https%3A%2F%2Ffinance.yahoo.com%2Fquote%2F%255EGSPC%2Fhistory');}</script><noscript><META http-equiv=\"refresh\" content=\"0;URL='https://www.yahoo.com/?err=404&err_url=https%3A%2F%2Ffinance.yahoo.com%2Fquote%2F%255EGSPC%2Fhistory'\"></noscript></html>")
    at C:\Users\bailw\projects\money_bot\node_modules\yahoo-finance\lib\yahooCrumb.js:72:13
    at tryCatcher (C:\Users\bailw\projects\money_bot\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\bailw\projects\money_bot\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\bailw\projects\money_bot\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\bailw\projects\money_bot\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\bailw\projects\money_bot\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (C:\Users\bailw\projects\money_bot\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\bailw\projects\money_bot\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\bailw\projects\money_bot\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (C:\Users\bailw\projects\money_bot\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21)
```

**Comment by gadicc** [comment]
Hey @leebailey88, thanks for the report.  Can you confirm if you still have this issue with https://github.com/gadicc/node-yahoo-finance2?  We stopped working on v1 a few years back.  There's an [UPGRADING](https://github.com/gadicc/node-yahoo-finance2/blob/devel/docs/UPGRADING.md) guide too.

**Comment by leebailey88** [comment]
Thanks for the quick response! It seems to be working fine on node-yahoo-finance2. I'm going to completely switch to the new library

**Comment by gadicc** [comment]
Great news!  Thanks for reporting back :pray:
